version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout

      - run:
          name: Install Docker client
          command: |
            sudo apt-get update
            sudo apt-get install -y docker.io

      - run:
          name: Build Docker image
          command: docker build -t flask-ci-cd .

      - run:
          name: Test run container
          command: docker run -d -p 5000:5000 flask-ci-cd

workflows:
  build_and_test:
    jobs:
      - build
