version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:current # Full VM with Docker pre-installed
    steps:
      - checkout

      - run:
          name: Build Docker image
          command: docker build -t flask-ci-cd .

      - run:
          name: Test run container
          command: docker run -d -p 5000:5000 flask-ci-cd

workflows:
  build_and_test:
    jobs:
      - build
